version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - btop
  - charliermarsh
  - cifs
  - dockercompose
  - dotenv
  - fgrep
  - geerlingguy
  - inquirypi
  - isort
  - kilolink
  - macmini
  - mccabe
  - mkdocs
  - mypy
  - passwordless
  - pipefail
  - pycodestyle
  - pyflakes
  - pygrep
  - pyupgrade
  - setuptools
  - tamasfe
  - tryceratops
  - venv
ignoreWords: []
import: []
