apiVersion: 1

datasources:
  - name: InfluxDB_v2
    uid: influxdb_v2
    type: influxdb
    access: proxy
    isDefault: true
    url: http://av_influxdb2:8086
    jsonData:
      version: Flux
      organization: docs
      defaultBucket: home
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_ADMIN_TOKEN}
